# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
    config.vm.box = "Ubuntu precise 64 VMWare"
    config.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"

    count = 1
    for i in 1..3    
    ip = count + 10
    config.vm.define "es#{i}" do |es1|
        es1.vm.network :hostonly, "192.168.50.#{ip}"
        es1.vm.provision :puppet do |puppet|
            puppet.module_path = './setup/modules'
            puppet.manifests_path = './setup/manifests'
            puppet.manifest_file = 'default.pp'
            puppet.options = '--verbose --debug'
        end
    end
    end
end 
