Vagrant.configure("2") do |config|
    config.vm.box = "Ubuntu precise 64 VMWare"
    config.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"
    config.vm.network :private_network, ip: "192.168.33.101"
    config.vm.provision "shell", inline: "sudo apt-get update"
end
