Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end

  config.vm.guest = :windows
  config.vm.box = "Windows 2008 R2"
  config.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07cVB5SE5CWVFPZzg/"

  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  #Set Up Networking
  config.vm.network "private_network", ip: "192.168.100.3"
  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985
end
