Vagrant.configure("2") do |config|

  config.vm.box = "win2008r2x64"
  config.vm.box_url = "https://googledrive.com/host/0B6J6sk4wHy07cVB5SE5CWVFPZzg/"
  config.vm.provider.gui = true

  # Max time to wait for the guest to shutdown
  config.windows.halt_timeout = 20

  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  # Configure base box parameters
  config.vm.guest = :windows

  #Set Up Networking
  config.vm.network :private_network, ip: "192.168.0.3"

end
